export const PUCK_RADIUS = 4;
export const SIZE_Y = 400;
export const SIZE_X = SIZE_Y * 2;
export const CORNER_R = 55;
export const CORNER_D = CORNER_R * 2;
export const CORNER_DRAW_R = 104;
export const BORDER_BLOCK_RADIUS = 16;
export const RADIAL_BLOCK_SHIFT = CORNER_D - BORDER_BLOCK_RADIUS;
export const BLOCK_AMOUNT = 64;